spring.application.name=notificaciones-api
server.port=${SERVER_PORT:8086}

#Data Source Properties
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db_notificaciones}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

#JPA Properties
spring.jpa.database=MYSQL
spring.jpa.properties.hibernate.format_sql=TRUE
spring.jpa.hibernate.ddl-auto=none

#Thymeleaf 
spring.thymeleaf.cache=false

#Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/actuator/info
springdoc.swagger-ui.enabled=true

#Configuracion para envio de email
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.test-connection=${MAIL_TEST_CONNECTION:false}

# Servicio persona
uri.service.persona=${URI_SERVICE_PERSONA:http://localhost:8084}
